### ISSUE TITLE
Can't get 'utf-8' encoding at timeline.ejs

### ISSUE THREAD

**Issue by anheew1** [teammoim/moim-node#4]
![image](https://user-images.githubusercontent.com/28583561/45973836-7e299e80-c07a-11e8-9893-c7b0df71d92b.png)

korean text is crashed.

**Comment by herdson** [comment]
Oh. That is critical problem. Anyone know solution?

**Comment by herdson** [comment]
![isolve](https://user-images.githubusercontent.com/10281005/45999891-ff684c00-c0e1-11e8-94db-4f84aa3c13d2.png)
I solved.
이 문제는 윈도우와 리눅스의 인코딩 차이에서 비롯되는 것으로 추측됨. 일단 리눅스 기준으로는 한글이 나오게 조치함.
